### ISSUE TITLE
induccion matematica

### ISSUE THREAD

**Issue by elisa1223** [SistemasTecTlaxiaco/actividad-9-practica-de-inducci-n-matem-tica-equipo-nestor-diego-elisa#1]
[induccion matematica.pdf](https://github.com/SistemasTecTlaxiaco/actividad-9-practica-de-inducci-n-matem-tica-equipo-nestor-diego-elisa/files/13221763/induccion.matematica.pdf)

**Comment by mayraglez917** [comment]
Portada: 25/25
Procedimiento: 25/25
Figuras, ilustraciones y fotografías: 15/25 (No contiene mínimo 10 figuras e ilustraciones del las actividades realizadas ).
Resultados y Conclusión: 20/25(No cuenta con la conclusión completa de 12 lineas de texto.)
Total: 85/100

Puntaje final: 17/20
Calificado por el equipo de Mayra, Diego, Félix, Daniel.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
